### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by huangyihe** [HewlettPackard/foedus_code#138]
Hi I'm having issues compiling the benchmarks. When running cmake, it complains:

```
CMake Error at third_party/gflags-2.1.1/CMakeLists.txt:129 (message):
  Do not know how to define a 32-bit integer quantity on your system! Neither
  uint32_t, u_int32_t, nor __int32 seem to be available.  Set
  GFLAGS_INTTYPES_FORMAT to either C99, BSD, or VC7 and try again.
```

I was able to bypass it by manually setting the `CFLAGS_INTTYPES_FORMAT` value in the cmake cache file, but the compilation fails at the last linking step about some errors with the `-fPIE` option.

Is my workaround of the cmake error correct, and where should I go to set the `-fPIE` compile time flag when building the `gflags` library?

I am building on Ubuntu 18.04 with gcc-7.3.

**Comment by huangyihe** [comment]
I figured it out by by disabling the `-fno-pie` cmake configuration which was said to be necessary for `gperftools`. Since I won't be using `gperftools` and don't have it installed I think this workaround is fine for my use.

**Comment by jacktong1989** [comment]
> I figured it out by by disabling the `-fno-pie` cmake configuration which was said to be necessary for `gperftools`. Since I won't be using `gperftools` and don't have it installed I think this workaround is fine for my use.

May I ask how you disable the cmake configuration? Specifically, which file did you edit?
